#!/usr/bin/env python3
"""Generate auditable Supplementary Sections 5 and 6 from frozen inputs.

The reference-set table is deliberately disclosure-safe: it uses corpus IDs
instead of repository names and omits source coordinates and exploit details.
The corpus table retains public third-party repository identities and complete
frozen commits for reproducibility.
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import Counter
from pathlib import Path
from typing import Any


BASE_DIR = Path(__file__).resolve().parent.parent
DEFAULT_GT = BASE_DIR / "analysis" / "ground_truth" / "reproduction_confirmed_gt.jsonl"
DEFAULT_QUEUE = BASE_DIR / "analysis" / "ground_truth" / "vulnerability_gt_upgrade_queue.jsonl"
DEFAULT_MANIFEST = BASE_DIR / "dataset" / "corpus_manifest.csv"
DEFAULT_OUTPUT_DIR = BASE_DIR / "analysis" / "paper" / "supplementary"

ADAPTER_ROWS = (
    ("MCP / FastMCP", "Python, TS/JS", "tool decorators; registerTool/server.tool"),
    ("LangChain", "Python, TS/JS", "@tool; Tool/StructuredTool factories; tool bindings"),
    ("CrewAI", "Python", "@tool; BaseTool._run/run"),
    ("AutoGen", "Python", "register_for_llm/register_for_execution"),
    ("OpenAI Agents SDK", "Python", "@function_tool"),
    ("Semantic Kernel", "Python", "@kernel_function"),
    ("LlamaIndex", "Python, TS/JS", "FunctionTool/QueryEngineTool factories"),
)


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def latex_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    replacements = {
        "\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$",
        "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}",
    }
    return "".join(replacements.get(char, char) for char in text)


def classify(row: dict[str, Any], queue_ids: set[str]) -> tuple[str, str]:
    if row.get("vulnerability_ground_truth"):
        return "vulnerability-level GT", "withheld during review"
    if row["gt_id"] in queue_ids or not row.get("not_a_vulnerability_claim"):
        return "boundary/disclosure pending", "withheld during review"
    return "negative control", "not applicable"


def evidence_level(proof_types: list[str]) -> str:
    proof = set(proof_types)
    levels: list[str] = []
    if proof & {"local_reproduction", "runtime_marker"}:
        levels.append("controlled runtime")
    if "runtime_stub_or_monkeypatch" in proof:
        levels.append("stub/monkeypatch")
    if "boundary_or_reachability" in proof:
        levels.append("boundary/reachability")
    if "source_trace" in proof:
        levels.append("source trace")
    return "; ".join(levels) or "confirmed record"


def build_reference_rows(
    gt_rows: list[dict[str, Any]], queue_rows: list[dict[str, Any]], manifest_rows: list[dict[str, str]]
) -> list[dict[str, Any]]:
    repo_ids = {row["repo"]: row["sample_id"] for row in manifest_rows}
    queue_ids = {row["gt_id"] for row in queue_rows}
    missing = sorted({row["repository"] for row in gt_rows} - set(repo_ids))
    if missing:
        raise ValueError(f"GT repositories missing from corpus manifest: {missing}")
    result = []
    for row in gt_rows:
        disposition, disclosure = classify(row, queue_ids)
        result.append(
            {
                "case_id": row["gt_id"],
                "repository_id": repo_ids[row["repository"]],
                "behavior_category": row["behavior_category"],
                "evidence_level": evidence_level(row.get("proof_types", [])),
                "disposition": disposition,
                "disclosure_status": disclosure,
                "auth_material_supplied": bool(row.get("auth_material_supplied")),
            }
        )
    return sorted(result, key=lambda row: row["case_id"])


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def write_latex(reference_rows: list[dict[str, Any]], manifest_rows: list[dict[str, str]], path: Path) -> None:
    ecosystems = Counter(row["ecosystem"] for row in manifest_rows)
    languages = Counter(row["dominant_language"] for row in manifest_rows)
    dispositions = Counter(row["disposition"] for row in reference_rows)
    lines = [
        r"% Generated by scripts/build_supplementary_reference_corpus.py.",
        r"% Preamble requirements: \usepackage{longtable,array}",
        r"\clearpage",
        r"\onecolumn",
        r"\section{Reproduction-Confirmed Behavior Reference Set}",
        r"The reference set contains 22 behavior cases supported by controlled evidence. It is not a list of 22 vulnerabilities. Repository identities are replaced by frozen corpus identifiers in this table, and source coordinates and exploit details are omitted. A vulnerability-level disposition denotes the paper's evidence threshold, not an assigned CVE. Pending disclosure details remain withheld during anonymous review.",
        "",
        r"\begin{longtable}{p{1.4cm}p{1.3cm}p{3.0cm}p{4.0cm}p{3.0cm}p{2.5cm}}",
        r"\caption{Disclosure-safe disposition of the reproduction-confirmed behavior reference set.}\label{tab:supp-reference-set}\\",
        r"\toprule",
        r"Case & Repo ID & Behavior & Evidence level & Disposition & Disclosure \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Case & Repo ID & Behavior & Evidence level & Disposition & Disclosure \\",
        r"\midrule",
        r"\endhead",
    ]
    for row in reference_rows:
        lines.append(
            " & ".join(
                latex_escape(row[key])
                for key in ("case_id", "repository_id", "behavior_category", "evidence_level", "disposition", "disclosure_status")
            ) + r" \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{longtable}",
            "",
            "The disposition totals are "
            + ", ".join(f"{latex_escape(name)}={count}" for name, count in sorted(dispositions.items()))
            + ". Human-review and model-panel labels are not used to establish these records.",
            "",
            r"\section{Corpus Manifest and Framework Coverage}",
            r"AgentSecBench freezes 67 public third-party repositories at 67 recorded commits. Inclusion used the risk-directed high-priority selection protocol described in the main paper. The manifest records repository identity, ecosystem, dominant language, commit, source-file statistics, and capture metadata. Repository names are retained for auditability; the authors must re-run the anonymity linkage check before submission.",
            "",
            r"\begin{table}[h]",
            r"\caption{Corpus ecosystem coverage.}",
            r"\label{tab:supp-ecosystems}",
            r"\centering\small",
            r"\begin{tabular}{lr}",
            r"\toprule Ecosystem & Repositories \\ \midrule",
        ]
    )
    for name, count in sorted(ecosystems.items(), key=lambda item: (-item[1], item[0])):
        lines.append(f"{latex_escape(name)} & {count} " + r"\\")
    lines.extend([r"\bottomrule\end{tabular}", r"\end{table}", ""])
    lines.extend(
        [
            r"\begin{table}[h]",
            r"\caption{Framework-adapter registry used by the normalization layer. Patterns are summarized; executable matching rules remain authoritative.}",
            r"\label{tab:supp-adapters}",
            r"\centering\small",
            r"\begin{tabular}{p{3.2cm}p{2.2cm}p{8.5cm}}",
            r"\toprule Framework & Languages & Recognized idioms \\ \midrule",
        ]
    )
    for framework, language, patterns in ADAPTER_ROWS:
        lines.append(
            f"{latex_escape(framework)} & {latex_escape(language)} & {latex_escape(patterns)} " + r"\\"
        )
    lines.extend(
        [
            r"\bottomrule\end{tabular}",
            r"\end{table}",
            "",
            r"\begin{longtable}{p{1.2cm}p{4.2cm}p{3.4cm}p{2.5cm}p{5.2cm}}",
            r"\caption{Complete frozen corpus manifest. Full commit hashes are reported; selection criterion is risk-directed high priority for every row.}\label{tab:supp-corpus-manifest}\\",
            r"\toprule ID & Repository & Ecosystem & Language & Frozen commit \\ \midrule",
            r"\endfirsthead",
            r"\toprule ID & Repository & Ecosystem & Language & Frozen commit \\ \midrule",
            r"\endhead",
        ]
    )
    for row in sorted(manifest_rows, key=lambda item: item["sample_id"]):
        lines.append(
            f"{latex_escape(row['sample_id'])} & {latex_escape(row['repo'])} & {latex_escape(row['ecosystem'])} & "
            f"{latex_escape(row['dominant_language'])} & "
            + r"\texttt{"
            + latex_escape(row["git_commit"])
            + r"} \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{longtable}",
            "",
            "Dominant-language counts are "
            + ", ".join(f"{latex_escape(name)}={count}" for name, count in languages.most_common())
            + ". The complete machine-readable manifest additionally records source-file counts, byte counts, commit dates, and snapshot metadata.",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ground-truth", type=Path, default=DEFAULT_GT)
    parser.add_argument("--upgrade-queue", type=Path, default=DEFAULT_QUEUE)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    args = parser.parse_args()
    gt_rows = read_jsonl(args.ground_truth)
    queue_rows = read_jsonl(args.upgrade_queue) if args.upgrade_queue.exists() else []
    manifest_rows = read_csv(args.manifest)
    if len(gt_rows) != 22:
        raise SystemExit(f"expected 22 frozen behavior-GT records, found {len(gt_rows)}")
    if len(manifest_rows) != 67:
        raise SystemExit(f"expected 67 frozen corpus records, found {len(manifest_rows)}")
    reference_rows = build_reference_rows(gt_rows, queue_rows, manifest_rows)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    reference_csv = args.output_dir / "reference_set_disclosure_safe.csv"
    manifest_csv = args.output_dir / "corpus_manifest_public.csv"
    latex_path = args.output_dir / "supplementary_sections_5_6.tex"
    write_csv(reference_csv, reference_rows)
    write_csv(manifest_csv, manifest_rows)
    write_latex(reference_rows, manifest_rows, latex_path)
    summary = {
        "status": "complete",
        "reference_cases": len(reference_rows),
        "reference_repositories": len({row["repository_id"] for row in reference_rows}),
        "corpus_repositories": len(manifest_rows),
        "ecosystems": len({row["ecosystem"] for row in manifest_rows}),
        "adapters": len(ADAPTER_ROWS),
        "dispositions": dict(sorted(Counter(row["disposition"] for row in reference_rows).items())),
        "outputs": {
            "reference_csv": str(reference_csv),
            "manifest_csv": str(manifest_csv),
            "latex": str(latex_path),
        },
    }
    (args.output_dir / "supplementary_sections_5_6_summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
